### ISSUE TITLE
#18. Herokでの公開

### ISSUE THREAD

**Issue by yasukun775** [yasukun775/original#19]

**Comment by yasukun775** [comment]
- terminalからherokuに初回ログインした際に発行されたURLとgitリポジトリ
    - https://cashflow-1.herokuapp.com/ | https://git.heroku.com/cashflow-1.git

**Comment by yasukun775** [comment]
- 末尾のエラーが発生
    - 環境
        - ruby 2.6.6
        - heroku 22?
            - `heroku -v` だと `heroku/7.63.4 linux-x64 node-v14.19.0`
    - `git push heroku main`
    
```
Enumerating objects: 207, done.
Counting objects: 100% (207/207), done.
Delta compression using up to 2 threads
Compressing objects: 100% (184/184), done.
Writing objects: 100% (207/207), 54.88 KiB | 4.22 MiB/s, done.
Total 207 (delta 29), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-22 stack
remote: -----> Determining which buildpack to use for this app
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:                         Detected buildpacks: Ruby,Node.js
remote:                         See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Ruby app detected
remote: -----> Installing bundler 1.17.3
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote:        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-2.6.6.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
remote:        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-22/ruby-2.6.6.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
remote: 
remote:  !
remote:  !     The Ruby version you are trying to install does not exist on this stack.
remote:  !     
remote:  !     You are trying to install ruby-2.6.6 on heroku-22.
remote:  !     
remote:  !     Ruby ruby-2.6.6 is present on the following stacks:
remote:  !     
remote:  !     - heroku-18
remote:  !     - heroku-20
remote:  !     
remote:  !     Heroku recommends you use the latest supported Ruby version listed here:
remote:  !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
remote:  !     
remote:  !     For more information on syntax for declaring a Ruby version see:
remote:  !     https://devcenter.heroku.com/articles/ruby-versions
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: 61ab6c7f4ef890747b9404879c20d821b5351968
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version 61ab6c7f4ef890747b9404879c20d821b5351968
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote: 
remote: Verifying deploy....
remote: 
remote: !       Push rejected to cashflow-1.
remote: 
To https://git.heroku.com/cashflow-1.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/cashflow-1.git'
```

**Comment by yasukun775** [comment]
- herokuをダウングレードする
    - rubyを3.x系にアップグレードすると動かなくなる可能性が高いらしいのでherokuのダウングレードで対応
    - heroku stack:set heroku-20 -a (app name)
        - app name はherokuに作成していたアプリケーション。今回はcashflow-1
    - しかしエラー・・・

```
Enumerating objects: 207, done.
Counting objects: 100% (207/207), done.
Delta compression using up to 2 threads
Compressing objects: 100% (184/184), done.
Writing objects: 100% (207/207), 54.80 KiB | 2.88 MiB/s, done.
Total 207 (delta 30), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Determining which buildpack to use for this app
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:                         Detected buildpacks: Ruby,Node.js
remote:                         See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Ruby app detected
remote: -----> Installing bundler 1.17.3
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.6.6
remote: -----> Installing dependencies using bundler 1.17.3
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 BUNDLE_GLOBAL_PATH_APPENDS_RUBY_SCOPE=1 bundle install -j4
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote:        Fetching gem metadata from https://rubygems.org/..........
remote:        Fetching rake 13.0.6
remote:        Installing rake 13.0.6
remote:        Fetching minitest 5.16.3
remote:        Fetching concurrent-ruby 1.1.10
remote:        Fetching thread_safe 0.3.6
remote:        Installing minitest 5.16.3
remote:        Installing thread_safe 0.3.6
remote:        Installing concurrent-ruby 1.1.10
remote:        Fetching builder 3.2.4
remote:        Installing builder 3.2.4
remote:        Fetching erubi 1.11.0
remote:        Installing erubi 1.11.0
remote:        Fetching mini_portile2 2.8.0
remote:        Fetching racc 1.6.0
remote:        Installing mini_portile2 2.8.0
remote:        Installing racc 1.6.0 with native extensions
remote:        Fetching crass 1.0.6
remote:        Installing crass 1.0.6
remote:        Fetching rack 2.2.4
remote:        Fetching nio4r 2.5.8
remote:        Installing rack 2.2.4
remote:        Installing nio4r 2.5.8 with native extensions
remote:        Fetching websocket-extensions 0.1.5
remote:        Installing websocket-extensions 0.1.5
remote:        Fetching mini_mime 1.1.2
remote:        Installing mini_mime 1.1.2
remote:        Fetching arel 9.0.0
remote:        Installing arel 9.0.0
remote:        Fetching marcel 1.0.2
remote:        Installing marcel 1.0.2
remote:        Fetching public_suffix 5.0.0
remote:        Installing public_suffix 5.0.0
remote:        Fetching execjs 2.8.1
remote:        Installing execjs 2.8.1
remote:        Fetching bcrypt 3.1.18
remote:        Installing bcrypt 3.1.18 with native extensions
remote:        Fetching msgpack 1.5.6
remote:        Installing msgpack 1.5.6 with native extensions
remote:        Fetching popper_js 1.16.0
remote:        Installing popper_js 1.16.0
remote:        Fetching method_source 1.0.0
remote:        Installing method_source 1.0.0
remote:        Fetching thor 1.2.1
remote:        Installing thor 1.2.1
remote:        Fetching ffi 1.15.5
remote:        Installing ffi 1.15.5 with native extensions
remote:        Fetching tilt 2.0.11
remote:        Installing tilt 2.0.11
remote:        Using bundler 1.17.3
remote:        Fetching chartkick 4.2.1
remote:        Installing chartkick 4.2.1
remote:        Fetching coffee-script-source 1.12.2
remote:        Installing coffee-script-source 1.12.2
remote:        Fetching connection_pool 2.3.0
remote:        Installing connection_pool 2.3.0
remote:        Fetching orm_adapter 0.5.0
remote:        Installing orm_adapter 0.5.0
remote:        Fetching unf_ext 0.0.8.2
remote:        Installing unf_ext 0.0.8.2 with native extensions
remote:        Fetching exonio 0.6.1
remote:        Installing exonio 0.6.1
remote:        Fetching mime-types-data 3.2022.0105
remote:        Installing mime-types-data 3.2022.0105
remote:        Fetching net-http-digest_auth 1.4.1
remote:        Installing net-http-digest_auth 1.4.1
remote:        Fetching rubyntlm 0.6.3
remote:        Installing rubyntlm 0.6.3
remote:        Fetching webrick 1.7.0
remote:        Installing webrick 1.7.0
remote:        Fetching webrobots 0.1.2
remote:        Installing webrobots 0.1.2
remote:        Fetching pg 1.4.3
remote:        Installing pg 1.4.3 with native extensions
remote:        Fetching puma 3.12.6
remote:        Installing puma 3.12.6 with native extensions
remote:        Fetching rb-fsevent 0.11.2
remote:        Installing rb-fsevent 0.11.2
remote:        Fetching turbolinks-source 5.2.0
remote:        Installing turbolinks-source 5.2.0
remote:        Fetching tzinfo 1.2.10
remote:        Installing tzinfo 1.2.10
remote:        Fetching i18n 1.12.0
remote:        Installing i18n 1.12.0
remote:        Fetching rack-test 2.0.2
remote:        Installing rack-test 2.0.2
remote:        Fetching sprockets 3.7.2
remote:        Installing sprockets 3.7.2
remote:        Fetching warden 1.2.9
remote:        Installing warden 1.2.9
remote:        Fetching websocket-driver 0.7.5
remote:        Installing websocket-driver 0.7.5 with native extensions
remote:        Fetching mail 2.7.1
remote:        Installing mail 2.7.1
remote:        Fetching addressable 2.8.1
remote:        Installing addressable 2.8.1
remote:        Fetching autoprefixer-rails 10.4.7.0
remote:        Installing autoprefixer-rails 10.4.7.0
remote:        Fetching uglifier 4.2.0
remote:        Installing uglifier 4.2.0
remote:        Fetching nokogiri 1.13.8 (x86_64-linux)
remote:        Installing nokogiri 1.13.8 (x86_64-linux)
remote:        Fetching coffee-script 2.4.1
remote:        Installing coffee-script 2.4.1
remote:        Fetching net-http-persistent 4.0.1
remote:        Installing net-http-persistent 4.0.1
remote:        Fetching bootsnap 1.13.0
remote:        Installing bootsnap 1.13.0 with native extensions
remote:        Fetching mime-types 3.4.1
remote:        Installing mime-types 3.4.1
remote:        Fetching sassc 2.4.0
remote:        Installing sassc 2.4.0 with native extensions
remote:        Fetching rb-inotify 0.10.1
remote:        Installing rb-inotify 0.10.1
remote:        Fetching unf 0.1.4
remote:        Installing unf 0.1.4
remote:        Fetching turbolinks 5.2.1
remote:        Installing turbolinks 5.2.1
remote:        Fetching activesupport 5.2.8.1
remote:        Installing activesupport 5.2.8.1
remote:        Fetching loofah 2.18.0
remote:        Installing loofah 2.18.0
remote:        Fetching sass-listen 4.0.0
remote:        Installing sass-listen 4.0.0
remote:        Fetching domain_name 0.5.20190701
remote:        Installing domain_name 0.5.20190701
remote:        Fetching rails-dom-testing 2.0.3
remote:        Installing rails-dom-testing 2.0.3
remote:        Fetching globalid 1.0.0
remote:        Fetching activemodel 5.2.8.1
remote:        Installing globalid 1.0.0
remote:        Installing activemodel 5.2.8.1
remote:        Fetching rails-html-sanitizer 1.4.3
remote:        Installing rails-html-sanitizer 1.4.3
remote:        Fetching sass 3.7.4
remote:        Installing sass 3.7.4
remote:        Fetching http-cookie 1.0.5
remote:        Installing http-cookie 1.0.5
remote:        Fetching activejob 5.2.8.1
remote:        Installing activejob 5.2.8.1
remote:        Fetching actionview 5.2.8.1
remote:        Installing actionview 5.2.8.1
remote:        Fetching activerecord 5.2.8.1
remote:        Installing activerecord 5.2.8.1
remote:        Fetching mechanize 2.8.5
remote:        Installing mechanize 2.8.5
remote:        Fetching jbuilder 2.11.5
remote:        Fetching actionpack 5.2.8.1
remote:        Installing jbuilder 2.11.5
remote:        Installing actionpack 5.2.8.1
remote:        Fetching actioncable 5.2.8.1
remote:        Fetching actionmailer 5.2.8.1
remote:        Installing actioncable 5.2.8.1
remote:        Installing actionmailer 5.2.8.1
remote:        Fetching activestorage 5.2.8.1
remote:        Installing activestorage 5.2.8.1
remote:        Fetching railties 5.2.8.1
remote:        Installing railties 5.2.8.1
remote:        Fetching sprockets-rails 3.4.2
remote:        Installing sprockets-rails 3.4.2
remote:        Fetching coffee-rails 4.2.2
remote:        Fetching responders 3.0.1
remote:        Installing coffee-rails 4.2.2
remote:        Installing responders 3.0.1
remote:        Fetching jquery-rails 4.5.0
remote:        Fetching rails 5.2.8.1
remote:        Installing rails 5.2.8.1
remote:        Installing jquery-rails 4.5.0
remote:        Fetching sass-rails 5.1.0
remote:        Installing sass-rails 5.1.0
remote:        Fetching devise 4.8.1
remote:        Installing devise 4.8.1
remote:        Fetching sassc-rails 2.1.2
remote:        Installing sassc-rails 2.1.2
remote:        Fetching bootstrap 4.6.1
remote:        Installing bootstrap 4.6.1
remote:        Bundle complete! 25 Gemfile dependencies, 88 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Post-install message from sass:
remote:        
remote:        Ruby Sass has reached end-of-life and should no longer be used.
remote:        
remote:        * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
remote:          primary implementation: https://sass-lang.com/install
remote:        
remote:        * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
remote:          sassc gem: https://github.com/sass/sassc-ruby#readme
remote:        
remote:        * For more details, please refer to the Sass blog:
remote:          https://sass-lang.com/blog/posts/7828841
remote:        
remote:        Bundle completed (185.51s)
remote:        Cleaning up the bundler cache.
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote: -----> Installing node-v16.13.1-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        Yarn executable was not detected in the system.
remote:        Download Yarn at https://yarnpkg.com/en/docs/install
remote:        I, [2022-09-20T09:34:47.385751 #1394]  INFO -- : Writing /tmp/build_410f62fc/public/assets/application-95b9be893fc1acc6ad98d884c09c8433ca8f64977e1fbcbb7c14419690afeb89.js
remote:        I, [2022-09-20T09:34:47.386142 #1394]  INFO -- : Writing /tmp/build_410f62fc/public/assets/application-95b9be893fc1acc6ad98d884c09c8433ca8f64977e1fbcbb7c14419690afeb89.js.gz
remote:        autoprefixer: /tmp/build_410f62fc/app/assets/stylesheets/application.scss:4195:3: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
remote:        I, [2022-09-20T09:34:50.583554 #1394]  INFO -- : Writing /tmp/build_410f62fc/public/assets/application-3c5b7b9c734755b06f113d7d4a8e08742c340f66c37e9ce95c65fec340b6320a.css
remote:        I, [2022-09-20T09:34:50.584039 #1394]  INFO -- : Writing /tmp/build_410f62fc/public/assets/application-3c5b7b9c734755b06f113d7d4a8e08742c340f66c37e9ce95c65fec340b6320a.css.gz
remote:        Asset precompilation completed (12.69s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: -----> Detecting rails configuration
remote: 
remote: ###### WARNING:
remote: 
remote:        Detecting rails configuration failed
remote:        set HEROKU_DEBUG_RAILS_RUNNER=1 to debug
remote: 
remote: ###### WARNING:
remote: 
remote:        There is a more recent Ruby version available for you to use:
remote:        
remote:        2.6.10
remote:        
remote:        The latest version will include security and bug fixes. We always recommend
remote:        running the latest version of your minor release.
remote:        
remote:        Please upgrade your Ruby version.
remote:        
remote:        For all available Ruby versions see:
remote:          https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
remote: 
remote: ###### WARNING:
remote: 
remote:        No Procfile detected, using the default web server.
remote:        We recommend explicitly declaring how to boot your server process via a Procfile.
remote:        https://devcenter.heroku.com/articles/ruby-default-web-server
remote: 
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> console, rake, web
remote: 
remote: -----> Compressing...
remote:        Done: 97.9M
remote: -----> Launching...
remote:        Released v7
remote:        https://cashflow-1.herokuapp.com/ deployed to Heroku
remote: 
remote: This app is using the Heroku-20 stack, however a newer stack is available.
remote: To upgrade to Heroku-22, see:
remote: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
remote: 
remote: Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.
remote: 
remote: If you have apps using any of these resources, you must upgrade to paid plans by this date to ensure your apps continue to run and to retain your data. For students, we will announce a new program by the end of September. Learn more at https://blog.heroku.com/next-chapter
remote: 
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: 61ab6c7f4ef890747b9404879c20d821b5351968
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version 61ab6c7f4ef890747b9404879c20d821b5351968
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote: 
remote: Verifying deploy.... done.
To https://git.heroku.com/cashflow-1.git
 * [new branch]      main -> main
```

**Comment by yasukun775** [comment]
- アプリケーション実行時のエラー
    - heroku run rails c
    - 下記の通り、durables.csvが見つかっていない？
        - これはseeds.rbに記載されているcsvファイル

```
Running rails c on ⬢ cashflow-1... up, run.3025 (Free)
Traceback (most recent call last):
        59: from /app/bin/rails:9:in `<main>'
        58: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        57: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        56: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/commands.rb:18:in `<main>'
        55: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/command.rb:46:in `invoke'
        54: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/command/base.rb:69:in `perform'
        53: from /app/vendor/bundle/ruby/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        52: from /app/vendor/bundle/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        51: from /app/vendor/bundle/ruby/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        50: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/commands/console/console_command.rb:95:in `perform'
        49: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        48: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/command/actions.rb:28:in `require_environment!'
        47: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/application.rb:337:in `require_environment!'
        46: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
        45: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        44: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
        43: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        42: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        41: from /app/config/environment.rb:5:in `<main>'
        40: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/application.rb:361:in `initialize!'
        39: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:60:in `run_initializers'
        38: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        37: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        36: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        35: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
        34: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
        33: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        32: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        31: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        30: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        29: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        28: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `run'
        27: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/initializable.rb:32:in `instance_exec'
        26: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        25: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:69:in `each'
        24: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:356:in `eager_load!'
        23: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `eager_load!'
        22: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:475:in `each'
        21: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `block in eager_load!'
        20: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:477:in `each'
        19: from /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.8.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        18: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:246:in `require_dependency'
        17: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:334:in `depend_on'
        16: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:356:in `require_or_load'
        15: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `load_interlock'
        14: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
        13: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        12: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        11: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        10: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'
         9: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `require'
         8: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:257:in `load_dependency'
         7: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies.rb:291:in `block in require'
         6: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         5: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         4: from /app/app/models/durable-save.rb:3:in `<main>'
         3: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:714:in `read'
         2: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:640:in `open'
         1: from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:640:in `open'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:640:in `initialize': No such file or directory @ rb_sysopen - durables.csv (Errno::ENOENT)
```

**Comment by yasukun775** [comment]
- 上記エラーのここが重要！
    - `4: from /app/app/models/durable-save.rb:3:in `<main>'`
    - このファイルが不要なファイルで存在しないパスを指定してしまっている
    - herokuだと全てのファイルを実行するっぽい
    - つまり不要なファイルは残さない！

**Comment by yasukun775** [comment]
- 上記のエラーはseedを別途migrateしなければならないことが原因！
    - `heroku run rake db:seed`
        - アプリをbuildしたうえで上記を実行しないとseedファイルが作成されない！

**Comment by yasukun775** [comment]
- これで公開された
- 注意点まとめ
    - ruby 2.6.6への変更
        - gemfileだけでなく、rvmで利用rubyを変更する必要あり
    - rubyとherokuバージョン次第でherokuがカバーしていないrubyバージョンになるとpushできない
        - herokuバージョンをダウングレードすること
    - テスト目的で適当に作ったファイルを残さない！
        - アプリbuildは完了してもそのファイルが原因でアプリが動かないことがある
    - db:migrateやdb:seed は別途実行しないとデータベースや初期データが用意されない！
