### ISSUE TITLE
#19. AWSでの公開

### ISSUE THREAD

**Issue by yasukun775** [yasukun775/original#23]

**Comment by yasukun775** [comment]
- 参考にするサイト
    - https://qiita.com/Yuki_Nagaoka/items/975b7598806d6ae0c0b2

**Comment by yasukun775** [comment]
## ネットワーク環境設定
- リージョンの変更
    - アジアパシフィック 東京
- VPCの作成 (VPC_for_cashflow)
    - AZを2つ作成・サブネットを更に2つずつ作成したがいったん削除
- 作成したVPCにサブネットを作成
    - cashflow_Subnet_1a
        - EC2用？
        -  IPv4 CIDR ブロック：10.0.0.0/24
    - cashflow_Subnet_1c
        - RDS用
        -  IPv4 CIDR ブロック：10.0.1.0/24
- インターネットゲートウェイの作成とVPCとの関連付け
    - Gateway_for_cashflow
    - VPC_for_cashflow にアタッチ (アクションから)
- ルートテーブルの作成とインターネットゲートウェイをルーティング
    - Table_for_cashflow
    - ルートを追加
        - 0.0.0.0/0
        - 上記で作成したインターネットゲートウェイ (Gateway_for_cashflow)
    - サブネットとのルートの追加
        - サブネットを選択して「ルートテーブルとの関連付け」を実施
        - 2つのサブネットにTable_for_cashflowを関連付ける
- セキュリティグループを作成
    - cashflow_SecurityGroup
    - VPC_for_cashflowと紐づけ
    - インバウンドルールの設定
        - タイプ：ssh、ソース：マイIP
        - タイプ：http、ソース：anywhere IPv4 (0.0.0.0/0)
        - タイプ：http、ソース：anywhere IPv6 (::/0)

**Comment by yasukun775** [comment]
## RDS設定
- サブネットグループの作成
    - cashflowDB-Subnet-Group
    - VPC_for_cashflowを関連付け
    - VPC_for_cashflow配下のサブネット2件を追加
- DBインスタンスの作成
    - 標準作成
    - PostgreSQL
    - バージョン
        - わからないが、13.7-R1に設定
    - 無料利用枠
    - cashflow-postgreSQL
    - マスタユーザ・パスワード
        - ファイルへ
    - インスタンス設定
        - バースト可能クラス db.t3.micro
        - これは無料利用枠だからかな？
    - ストレージ
        - プロビジョンドIOPS SSD
    - 接続
        - VPC_for_cashflow
        - cashflowdb-subnet-group
        - cashflow-SecurityGroup
        - パブリックアクセス：なし
        - データベースポート：5432
            - postgreのポート番号らしい
    - 追加設定
        - 最初のDB名
            - cashflow_production

**Comment by yasukun775** [comment]
## EC2インスタンス
- インスタンス作成
    - インスタンスタイプ
        - Amazon Linux 2 AMI (HVM) - Kernel 5.10 SSD Volume Type
            - 無料枠利用可能
        - 64bit x86
        - t2.micro
    - キーペアを作成
        - キーペア名：cashflow
        - cashflow.pem を取得
    - ネットワーク設定
        - VPC_for_cashflow
        - cashflow-subnet-1a
        - cashflow_SecurityGroup
    - ストレージ設定 (初期値のまま)
        - 1x 8GB gp2 ルートボリューム
    - 高度な設定
        - テナンシー：共有
        - 終了保護：有効化
        - シャットダウン動作：停止
        - キャパシティの予約：開く
    - 概要
        - インスタンス数：1

## Elastic IP
- Elastic IPを作成
    - IPアドレス　13.230.231.46
- IPアドレスの関連付け
    - cashflow-inistance01
    - プライベートIPアドレス　10.0.0.201

**Comment by yasukun775** [comment]
- 気になるところ
    - RDSのpostgreSQLバージョンを1.3.7から1.4.4に変更したつもりだが反映させていない
        - もしかすると作り直した方がよいかも？

**Comment by yasukun775** [comment]
- UbuntuにHomeBrewをインストール
    - https://zenn.dev/akgcog/articles/2e63b33ee3001a
    - apt-get install build-essential procps curl file git
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - next step
        - echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/yasuhirosuzuki/.profile
        - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        - sudo apt-get install build-essential
        - brew install gcc
    - バージョン確認しパスが通っていることを確認
        - brew --version
            - Homebrew 3.6.2

**Comment by yasukun775** [comment]
- EC2接続の下準備
    - PythonとPython関連パッケージのインストール
        - brew install python
            - python3 --version
                - Python 3.10.6
        - sudo apt-get install python-setuptools
            - easy_installができないので、これをインストール
            - それでもできない
            - easy_installはあきらめる
        - pip のインストール
            - sudo apt install python3-pip
            - pip -V
                - pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
        - nose
            - pip install nose
                - Successfully installed nose-1.3.7
                - しかしphthon3しか動いてなさそうだけど大丈夫か？
        - tornado
            - pip install tornado
                - Successfully installed tornado-6.2
        - awscli
            - sudo -H pip install awscli --upgrade --ignore-installed six
            - Successfully installed PyYAML-5.4.1 awscli-1.25.80 botocore-1.27.79 colorama-0.4.4 docutils-0.16 jmespath-1.0.1 pyasn1-0.4.8 python-dateutil-2.8.2 rsa-4.7.2 s3transfer-0.6.0 six-1.16.0 urllib3-1.26.12
            - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by yasukun775** [comment]
- EC2インスタンスへの接続 (pemでの接続とssh接続)
    - pemファイルでのec2のデフォルトユーザ (ec2-user) への接続
        - ローカルのHomeディレクトリ直下に.sshディレクトリを作成
            - mkfir .ssh
        - pemファイルをローカルから上記の.sshディレクトリへ移動
            - /mnt/c/Users/suzuk/Downloadsに存在する場合はそこに移動してから
            - mv cashflow.pem ~/,ssh
            - これでEC2接続用の鍵がubuntuの正しい位置に設定された
        - pemファイルの権限を600に設定
            - chmod 600 cashflow.pem
            - ssh系の鍵ファイルはこの権限にする必要がある
        - ec2-userに接続
            - ssh -i アプリ名.pem ec2-user@Elastic IP
            - ssh -i cashflow.pem ec2-user@13.230.231.46
                - ec2-userはEC2のデフォルトユーザの名前
                - 13.230.231.46はEC2インスタンス(サーバ)のホスト名 (IPアドレスがホスト名になっている)
                    - どちらもEC2インスタンスの「接続」から確認可能
    - ssh接続 (任意のEC2内のユーザへ)
        - EC2に任意のユーザを作成
            - ec2-userでEC2インスタンスに接続している状態で
            - sudo adduser yasukun
            - sudo passwd yasukun
        - 作成したユーザーに権限を追加する
            - sudo visudo
                - root   ALL=(ALL)       ALL の下の行に
                - ユーザ名   ALL=(ALL)       ALL を追加
                    - yasukun   ALL=(ALL)       ALL
        - これでユーザを切り替えられる
            - sudo su - yasukun
        - ssh接続元マシン (ローカル・ubuntu) に秘密鍵を作成
            - home/.ssh
                - ssh-keygen -t rsa
                    - (アプリ名)_key_rsa
                    - cashflow_key_rsa
                    - パスワードはなしでOK
        - どの通信で今回使った鍵を使うのか指定する
            - home/.ssh
                - vi config で末尾の記述を追加しconfigを新規作成
            - home/.ssh/cashflow_key_rsa.pub
                - 中身を全てコピーする
        - EC2に公開鍵を設置 (home/.ssh/authorized_keys)
            - ec2-user でログインし yasukunにユーザ切り替え
            - .sshディレクトリを作成
                - mkdir .ssh
            - .sshディレクトリの権限を変更
                - chmod 700 .ssh
            - .sshディレクトリに移動し公開鍵ファイルを作成
                - vi authorized_keys
                - コピーしていた cashflow_key_rsa.pub の中身を張り付ける
                    - コピペでターミナルに張り付けると先頭文字が欠けるケースがあるので注意！
            - authorized_keysファイルの権限を変更
                - chmod 600 authorized_keys
    - 権限付与やファイル配置も決まり通りに正しく行うこと。それができないとssh接続できない！
        - xxx_rsaやauthorized_keysの権限は600にすること
        - authorized_keysを格納する.sshディレクトリはhomeディレクトリ配下に置く
        - .sshディレクトリは権限を700に


```
Host アプリ名_key_rsa
  Hostname EC2のElastic IP(IPアドレス)
  Port 22
  User ユーザ名 #さっき作ったEC2ユーザ
  IdentityFile ~/.ssh/アプリ名_key_rsa #今回作成した秘密鍵

Host cashflow_key_rsa
  Hostname 13.230.231.46
  Port 22
  User ユーザ名 yasukun
  IdentityFile ~/.ssh/cashflow_key_rsa
```

**Comment by yasukun775** [comment]
- ec2でのnginxのインストールと設定
    - 下記サイトの通り実行
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
        - `1.各種プラグインのインストール`まで

- postgresqlのインストール
    - 下記サイトの通り実行
        - https://zenn.dev/uotohotaru/articles/0730f90dbf7a6d
        - ただし`postgresユーザーのパスワード設定`以降は実行していない

**Comment by yasukun775** [comment]
- node.js 6 のインストール
    - curl -sL https://rpm.nodesource.com/setup_6.x | sudo bash -
        - node.js 6 はもうサポート終了というWarningが出ている
        - * https://rpm.nodesource.com/setup_12.x - Node.js v12 LTS "Erbium"
        - * https://rpm.nodesource.com/setup_14.x - Node.js v14 LTS "Fermium" (recommended)
        - * https://rpm.nodesource.com/setup_16.x - Node.js v16 "Gallium"
    - sudo yum -y install nodejs
    - yum install nodejs --enablerepo=epel
        - 下記のエラー
            - Error getting repository data for epel, repository not found
            - repositoryがepelにないよ、とのこと

**Comment by yasukun775** [comment]
- rbenv のインストール
    - rbenvとはアプリケーションのRuby環境を整えるツール
        - [このサイト参照](https://mogulla3.tech/articles/2021-07-10-understanding-rbenv-1#:~:text=rbenv%E3%81%A8%E3%81%AF%20%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AERuby%E7%92%B0%E5%A2%83%E3%82%92%E6%95%B4%E3%81%88%E3%82%8B%E3%83%84%E3%83%BC%E3%83%AB%20%E3%81%A7%E3%81%99%E3%80%82)
    - 以下のサイト通りに実行
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
        - ただしrubyバージョンは2.6.6

**Comment by yasukun775** [comment]
- ToDo
    - 上記サイトがmysqlなので、postgresSQLの場合のエンドポイントの設定とpostgreSQLへのログインから実行

**Comment by yasukun775** [comment]
- postgreSQL
    - セキュリティグループの設定は以下のサイト通りに実行
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
    - エンドポイントを利用してubuntu (ec2ログイン済) からpostgreSQLにログインするのは以下のサイト通りに実行
        - https://qiita.com/nyainyai/items/02718d355f91ee42ce3d
        - `psql -h (postgreSQLのエンドポイント@RDS画面) -U root -d postgres`
            - dオプション後をRDSのDB識別子にはしない。これはDB名ではない。postgresが正解
    - ★postgresはかなりコマンドが違うっぽい？
        - データベース一覧の確認は `show databases;` ではなく `\l (￥とLの小文字)`

**Comment by yasukun775** [comment]
- Rubyファイル設置のためのGitとの接続
    - 以下のサイト通りに実行
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
            - 途中で出てくるchownの変数のユーザ名はec2ユーザの名前。当然だけど念のため…
    - ssh -T git@github.com
        - Hi yasukun775! You've successfully authenticated, but GitHub does not provide shell access.
            - アクセスできた

**Comment by yasukun775** [comment]
- railsファイルの実行
    - `/var/www/rails`
        - `bundle install`
        - 以下のエラーが発生
            - `rbenv: version `ruby-2.6.3' is not installed (set by /var/www/rails/original/.ruby-version)`
        - cloud9上では、`rvm --default 2.6.6` でrubyバージョンを2.6.6に変更すれば実行できていた
        - EC2のRubyバージョンは2.6.6となっているのを確認済
        - なのになぜ2.6.3がインストールされていないことが問題なのか？が不明な状態

**Comment by yasukun775** [comment]
- アプリのシークレット作成
    - `bundle install` で `rails new` されると `credentials.yml.enc` が EC2の `(アプリディレクトリ)/config` に作成される
    - この `credentials.yml.enc` を編集する必要がある
    - ただし `credentials.yml.enc` は `master.key`がないと編集できない
    - `master.key` は ローカルのアプリディレクトリには作成されるが`gitignore`のためgitにはpushされず、cloneしてもEC2側には転送されない
    - よって手動でローカルの `master.key` の内容をコピーして利用する必要がある

**Comment by yasukun775** [comment]
- ToDo
    - Nginxの設定@EC2
        - /etc/nginx/conf.d のファイルを編集せよとのことだが、どうもファイルが存在しない
        - nginx.conf か？要調査
    - また上記のsecretの設定がうまくいっているかもよくわからん
        - master.keyはOKぽい。なぜなら credential.yml.enc を編集できているから

**Comment by yasukun775** [comment]
- GemfileをローカルとEC2で確認して内容に相違がないか確認しよう

**Comment by yasukun775** [comment]
- Nginx・Unicornの設定
    - 基本は以下のサイト通りに実行
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
    - 気になるポイント
        - nginx.conf ではなく nginx/conf.d/original.conf で設定ファイルを作成している点

**Comment by yasukun775** [comment]
- postgresの設定
    - 本番環境(EC2)のdatabase.ymlを直接編集しているので、今後ローカルにも反映させる必要がある
        - そうしないとgit clone時にデグレードする
    - /var/www/rails/original/config/database.yml
        - 末尾のコードを追加
```
production:
  <<: *default 
  database: sample_app_production
  username: postgres # RDS DBインスタンスのユーザー名
  password: password # RDS DBインスタンスのパスワード
  host: xxxx.xxxx.ap-northeast-1.rds.amazonaws.com # RDS DBインスタンスのエンドポイント
```

**Comment by yasukun775** [comment]
- DBをmigrate
    - rails db:migrate RAILS_ENV=production
        - 実行結果は末尾でちゃんと実行できているっぽい
    - テーブルを確認する
        - psql -h cashflow-postgresql.cfzsatfsoxvm.ap-northeast-1.rds.amazonaws.com -U root -d postgres
        - \c cashflow_production
        - \dt
            - エラー `did not find any relations` テーブルが存在していない・・・なぜ？

```
== 20220908144356 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0020s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0006s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0007s
== 20220908144356 DeviseCreateUsers: migrated (0.0038s) =======================

== 20220909050716 CreateEstates: migrating ====================================
-- create_table(:estates)
   -> 0.0017s
== 20220909050716 CreateEstates: migrated (0.0019s) ===========================

== 20220909051224 CreateInitials: migrating ===================================
-- create_table(:initials)
   -> 0.0015s
== 20220909051224 CreateInitials: migrated (0.0017s) ==========================

== 20220909051329 CreateRunnings: migrating ===================================
-- create_table(:runnings)
   -> 0.0013s
== 20220909051329 CreateRunnings: migrated (0.0015s) ==========================

== 20220909051535 CreateReviews: migrating ====================================
-- create_table(:reviews)
   -> 0.0013s
== 20220909051535 CreateReviews: migrated (0.0015s) ===========================

== 20220909052000 CreateProfits: migrating ====================================
-- create_table(:profits)
   -> 0.0016s
== 20220909052000 CreateProfits: migrated (0.0018s) ===========================

== 20220909052321 CreateRebuilds: migrating ===================================
-- create_table(:rebuilds)
   -> 0.0015s
== 20220909052321 CreateRebuilds: migrated (0.0016s) ==========================

== 20220909053456 CreateDurables: migrating ===================================
-- create_table(:durables)
   -> 0.0014s
== 20220909053456 CreateDurables: migrated (0.0015s) ==========================

== 20220909053733 CreateTaxrates: migrating ===================================
-- create_table(:taxrates)
   -> 0.0017s
== 20220909053733 CreateTaxrates: migrated (0.0018s) ==========================

== 20220909053815 CreateAgings: migrating =====================================
-- create_table(:agings)
   -> 0.0006s
== 20220909053815 CreateAgings: migrated (0.0007s) ============================

== 20220909152739 RenameTypeColumnToEstate: migrating =========================
-- rename_column(:estates, :type, :estate_type)
   -> 0.0114s
== 20220909152739 RenameTypeColumnToEstate: migrated (0.0116s) ================

== 20220909153156 RenameTypeColumnToRebuild: migrating ========================
-- rename_column(:rebuilds, :type, :estate_type)
   -> 0.0048s
== 20220909153156 RenameTypeColumnToRebuild: migrated (0.0049s) ===============

== 20220909153232 RenameTypeColumnToDurable: migrating ========================
-- rename_column(:durables, :type, :estate_type)
   -> 0.0047s
== 20220909153232 RenameTypeColumnToDurable: migrated (0.0049s) ===============

== 20220909153332 RenameTypeColumnToAging: migrating ==========================
-- rename_column(:agings, :type, :estate_type)
   -> 0.0050s
== 20220909153332 RenameTypeColumnToAging: migrated (0.0051s) =================

== 20220909154440 AddUseridToEstates: migrating ===============================
-- add_column(:estates, :user_id, :integer)
   -> 0.0016s
== 20220909154440 AddUseridToEstates: migrated (0.0017s) ======================

== 20220913015532 AddExpectPriceToEstate: migrating ===========================
-- add_column(:estates, :expect_price, :integer)
   -> 0.0015s
== 20220913015532 AddExpectPriceToEstate: migrated (0.0017s) ==================

== 20220913015747 RemoveExpectPricesFromEstate: migrating =====================
-- remove_column(:estates, :expect_land_price, :integer)
   -> 0.0075s
-- remove_column(:estates, :expect_house_price, :integer)
   -> 0.0062s
== 20220913015747 RemoveExpectPricesFromEstate: migrated (0.0140s) ============

== 20220913094102 CreateDeductons: migrating ==================================
-- create_table(:deductons)
   -> 0.0015s
== 20220913094102 CreateDeductons: migrated (0.0017s) =========================

== 20220913094410 ChangeDeductonsToDeductions: migrating ======================
-- rename_table(:deductons, :deductions)
   -> 0.0027s
== 20220913094410 ChangeDeductonsToDeductions: migrated (0.0029s) =============

== 20220915062926 RenameBuyTaxLanColumnToBuyTaxLand: migrating ================
-- rename_column(:initials, :buy_tax_lan, :buy_tax_land)
   -> 0.0056s
== 20220915062926 RenameBuyTaxLanColumnToBuyTaxLand: migrated (0.0058s) =======

== 20220922070927 AddAccumulateToProfits: migrating ===========================
-- add_column(:profits, :accumulate_pl, :integer)
   -> 0.0015s
-- add_column(:profits, :accumulate_cf, :integer)
   -> 0.0005s
== 20220922070927 AddAccumulateToProfits: migrated (0.0023s) ==================

== 20220922071958 AddAccumulateresaleToProfits: migrating =====================
-- add_column(:profits, :accumulate_pl_resale, :integer)
   -> 0.0015s
-- add_column(:profits, :accumulate_cf_resale, :integer)
   -> 0.0005s
== 20220922071958 AddAccumulateresaleToProfits: migrated (0.0023s) ============

== 20220922072834 AddAccumulatecfresaleToProfit: migrating ====================
-- add_column(:profits, :roi_cf_resale, :integer)
   -> 0.0014s
== 20220922072834 AddAccumulatecfresaleToProfit: migrated (0.0016s) ===========
```

**Comment by yasukun775** [comment]
- 上記エラーは解決した
    - database.ymlへの追記 (おそらくこちらが解決)
        - 末尾の通り、adopterが必要
    - gem install pg;rbenv rehash の実行 (あまり関係ないだろう)

```
database.yml の末尾

production:
  <<: *default
  adapter: postgresql
  database: cashflow_production
  username: root
  password: cashflowyasu1214
  host: cashflow-postgresql.cfzsatfsoxvm.ap-northeast-1.rds.amazonaws.com

```

**Comment by yasukun775** [comment]
- ここからSTEP4
    - https://qiita.com/Yuki_Nagaoka/items/1f0b814e52e603613556

**Comment by yasukun775** [comment]
- ロードバランサ
    - Apllication Load Balancer
    - Target Group は Createボタンから別画面を開いて作成
        - ELB作成前にListnerにTargetGroupを関連付ける必要あり

**Comment by yasukun775** [comment]
- Railsアプリの起動
    - bundle exec rake assets:precompile RAILS_ENV=production
    - 以下のエラー。node js がダメっぽいな

```
rake aborted!
Your nodejs binary failed to load autoprefixer script file,
please check if you're running a supported version (10, 12, 14+)
```

**Comment by yasukun775** [comment]
- node.jsのアップデート
    - https://prograshi.com/framework/nodejs/nvm-install-update-node/
    - 長期安定版をインストール
    - nvmをインストール
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - nvmを有効にする
        - . ~/.nvm/nvm.sh
    - nvmの安定版をインストール
        - nvm install --lts
    - バージョン確認
        - nvm ls
        - v16.17.1 が有効となっている

**Comment by yasukun775** [comment]
- 再度アプリをビルドする
    - プリコンパイル
        - bundle exec rake assets:precompile RAILS_ENV=production
            - できている雰囲気。エラーはでない
    - Unicornを起動
        - bundle exec unicorn_rails -c /var/www/rails/アプリ名/config/unicorn.conf.rb -D -E production
            - 下記のエラー

```
precompile

Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
autoprefixer: /var/www/rails/original/app/assets/stylesheets/application.scss:4195:3: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
I, [2022-09-27T09:05:33.299730 #26471]  INFO -- : Writing /var/www/rails/original/public/assets/application-3c5b7b9c734755b06f113d7d4a8e08742c340f66c37e9ce95c65fec340b6320a.css
I, [2022-09-27T09:05:33.300216 #26471]  INFO -- : Writing /var/www/rails/original/public/assets/application-3c5b7b9c734755b06f113d7d4a8e08742c340f66c37e9ce95c65fec340b6320a.css.gz
```

```
Unicorn起動エラー

bundler: failed to load command: unicorn_rails (/home/yasukun/.rbenv/versions/2.6.6/bin/unicorn_rails)
NameError: undefined local variable or method `lets' for #<Unicorn::Configurator:0x000000000166afe8>
  /var/www/rails/original/config/unicorn.conf.rb:1:in `reload'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/lib/unicorn/configurator.rb:85:in `instance_eval'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/lib/unicorn/configurator.rb:85:in `reload'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/lib/unicorn/configurator.rb:78:in `initialize'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:78:in `new'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:78:in `initialize'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/bin/unicorn_rails:209:in `new'
  /home/yasukun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/unicorn-6.1.0/bin/unicorn_rails:209:in `<top (required)>'
  /home/yasukun/.rbenv/versions/2.6.6/bin/unicorn_rails:23:in `load'
  /home/yasukun/.rbenv/versions/2.6.6/bin/unicorn_rails:23:in `<top (required)>'
master failed to start, check stderr log for details
```

**Comment by yasukun775** [comment]
- 調べたいこと
    - Elastic IP (13.230.231.46) にプライベートIP (10.0.0.201) を紐づける意味
        - そもそもプライベートIPてなに？
    - Unicorn ってなに？
    - アプリのシークレットってなに？どんな意味があるの？
    - railsファイルのコンパイルになぜnode.jsが必要なの？
    - なぜ最初にpythonとかをインストールしたの？

**Comment by yasukun775** [comment]
- 環境変数 (.envファイル) を作成
    - 以下のサイト通り
        - https://qiita.com/Yuki_Nagaoka/items/dbb185feb6d4f051c2f2
    - シークレットキーってどういう位置づけなのかな？
